### PR TITLE
Fix behaviour when the destination file is deleted

### LINKED ISSUE #20: Behavior when output file is deleted while LS is running
From a user:
----------------------------------------------------------------------
if I delete an output file that Logstash has been writing to while it is running it does not recreate that file, and it does not error. It just acts like everything is fine and drops all the messages.

This is a bit concerning.

Is there anyway to change this default behavior to create the file if it is missing? Or at least throw an to error?

Steps to reproduce: 
- start up logstash with file output 
- send in input so it creates an output file 
- delete that output file 
- send some more data in 
- logstash will not complain, but no data will be written

Restarting logstash makes it find those files again.

### PR DESCRIPTION
**Pull request by purbon**
### Context

As commented out in #20, if during the time LS is running the destination file is deleted by another agent in the machine, the plugin takes the event without any kind of feedback. This makes the plugin behaviour awkward and confusing, including data loss.

### Reason

This happen because the plugin caches the file objects without doing any maintenance in case the file got deleted.  There is a check for something similar at ```close_stale_files``` function, but this might not make it on time.

### Fix

Add a new variable (```create_if_deleted```) to control the behaviour and make the open function react to it. Also include an option to forward events to the failure file in case this new variable is set to false. This enhancements make feedback always there, either by adding the files again to the destination file or using the failure file, there is also logging added.

Fixes #20

### CODE REVIEW

File: lib/logstash/outputs/file.rb [hunk 1]
```diff
@@ -198,9 +207,27 @@ def close_stale_files
...
+  end
 
+  private
+  def deleted?(path)
+    !File.exist?(path)
+  end
+
+  private
+  def open(path)
+    if !deleted?(path) && cached?(path)
```
Comment (jordansissel) [inline lib/logstash/outputs/file.rb]: This introduces up to 2 File.stat calls _per event_ sent to this output where previously there were zero File.stat calls per event.

I wonder about the performance implications of this.

Maybe we should only bother checking if the file is deleted if `@create_if_deleted` is true, that way the performance penalty is isolated to those wishing to use this 'create-if-deleted' behavior?

File: spec/outputs/file_spec.rb [hunk 2]
```diff
@@ -106,6 +107,58 @@
...
+          10.times do |i|
+            event = LogStash::Event.new("event_id" => i)
+            output.receive(event)
+          end
+          FileUtils.rm(temp_file)
+          10.times do |i|
+            event = LogStash::Event.new("event_id" => i+10)
+            output.receive(event)
+          end
+          expect(FileTest.exist?(temp_file.path)).to be_falsey
```
Comment (jordansissel) [inline spec/outputs/file_spec.rb]: Alternate way to write this, not sure if you like it:

```
expect(FileTest).not_to be_exist(temp_file.path)
```

(I think in this case, my alternative is more confusing, so let's ignore it, hehe)

**Comment by jordansissel** [comment]
Tests pass. Code LGTM. One comment about the performance impact of doing 2 stat syscalls per event.

File: spec/outputs/file_spec.rb (hunk 2 above)
Comment (purbon) [inline spec/outputs/file_spec.rb]: I think your solution is better in terms of being syntactically correct  and probably giving a better error message. But is also more confusing to read, so I would stick to the current one.

File: lib/logstash/outputs/file.rb (hunk 1 above)
Comment (purbon) [inline lib/logstash/outputs/file.rb]: this is a fair concert, however I added another "feature" here, if the file is deleted but ```@create_if_deleted``` is false, it appends the data to the failure file, like this there is no chance stuff is "lost". What do you think?

**Comment by purbon** [comment]
@jordansissel amended the code to track your performance concerns, so we get the same behaviour with less system calls.

**Comment by purbon** [comment]
Amended my last commit, because this will make the situation where the error file is deleted not being recreated again, I think this might be a bug. Lets release the plugin like this and improve the situation if required.
